/* eslint-disable import/prefer-default-export */

export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const CREATE_NEW_ROW = 'CREATE_NEW_ROW';
export const CREATE_NEW_COL = 'CREATE_NEW_COL';
export const RECEIVE_STOPWATCH_TIME = 'RECEIVE_STOPWATCH_TIME';
export const RECEIVE_STOPWATCH_NAME = 'RECEIVE_STOPWATCH_NAME';
export const DELETE_ROW = 'DELETE_ROW';
export const RECEIVE_STOPWATCH_TYPE = 'RECEIVE_STOPWATCH_TYPE';
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const CREATE_NEW_SESSION = 'CREATE_NEW_SESSION';
